# Generated by Django 3.1 on 2020-09-07 12:52

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_id', models.CharField(max_length=10)),
                ('ticket_name', models.CharField(max_length=300)),
                ('ticket_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar')),
                ('ticket_description', models.CharField(default='ticket description', max_length=1500)),
                ('ticket_price', models.CharField(default='100', max_length=20)),
                ('ticket_availability', models.CharField(default='No', max_length=10)),
                ('ticket_stock', models.IntegerField(default='0')),
            ],
        ),
        migrations.AlterField(
            model_name='purchase_details',
            name='time_of_purchase',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 7, 18, 22, 46, 46126)),
        ),
    ]
